---
AWSTemplateFormatVersion: '2010-09-09'
Description: cloudwatch-subscription-elasticsearch

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref DeploymentBucket
  BucketArn:
    Value: !GetAtt DeploymentBucket.Arn