---
AWSTemplateFormatVersion: '2010-09-09'
Description: cloudwatch-subscription-elasticsearch

Parameters:
  VpcId:
    Description: The VPC id
    Type: String
  PrivateSubnetIds:
    Description: The private subnet ids
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ElasticSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0

  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '6.3'
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType: t2.small.elasticsearch
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: '*'
          Action: es:*
          Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      VPCOptions:
        SubnetIds: !Ref PrivateSubnetIds
        SecurityGroupIds:
          - !Ref ElasticSearchSecurityGroup

Outputs:
  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn
  DomainName:
    Value: !Ref ElasticsearchDomain