template_path: templates/cloudwatch.yaml
dependencies:
  - example/bucket
parameters:
  VpcId: !stack_output vpc::VpcId
  PrivateSubnetIds: !stack_output vpc::PrivateSubnetIds
  S3Bucket: !stack_output bucket::BucketName
  S3Key: lambda.zip
  S3Version: !s3_version bucket::BucketName/lambda.zip
  DomainEndpoint: !stack_output elasticsearch::DomainEndpoint
sceptre_user_data:
  S3_Bucket: !stack_output bucket::BucketName
  S3_Key: lambda.zip
  S3_Version: !s3_version bucket::BucketName/lambda.zip
hooks:
  before_create:
    - !s3_upload_file dist/lambda.zip lambda.zip bucket::BucketName
  before_update:
    - !s3_upload_file dist/lambda.zip lambda.zip bucket::BucketName